services:
  mysql:
    container_name: 'db-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=calendarian-db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  hilla:
    container_name: 'hilla'
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'